apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: arjunreddy2304/calculator:latest  # Replace with your Docker Hub username/image name:tag
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred  # The name of the created secret
